[PayConfig]
sdk_http_port=":9080" # 对外公开
dynamo_db_pay_index = "uid-tistatus-index"
SentryDSN="https://be6857e4cfd8492faaecb01944f28e08:0b562b7924074c2181ed45868eaefc47@sentry.io/111080"

[[PayService]]
name="ios"

[PayService.Mail.PROD]
db_name="Mail_G207"
dynamo_region="ap-northeast-2"
db_driver= "DynamoDB"
mongo_url="127.0.0.1"

[PayService.SDK.ENJOYKO]
sdk_url_rel_path="enjoyko/ios/v1/billingcb"
params = ["32799f47d69801a4d2f238a5fcad811f"]

[PayService.Pay.PROD]
db_name="QuickPay_G207"
dynamo_region="ap-northeast-2"
db_driver= "DynamoDB"
mongo_url="127.0.0.1"


[[PayService]]
name="android"

[PayService.SDK.ENJOYKO]
sdk_url_rel_path="enjoyko/android/v1/billingcb"
params = ["32799f47d69801a4d2f238a5fcad811f"]

[PayService.Mail.PROD]
db_name="Mail_G207"
dynamo_region="ap-northeast-2"
db_driver= "DynamoDB"
mongo_url="127.0.0.1"

[PayService.Pay.PROD]
db_name="QuickPay_G207"
dynamo_region="ap-northeast-2"
db_driver= "DynamoDB"
mongo_url="127.0.0.1"

