// Code generated by protoc-gen-go.
// source: ProtobufGen_pay.proto
// DO NOT EDIT!

package ProtobufGen

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type PAY struct {
	// * 货物数字ID
	IID *uint32 `protobuf:"varint,1,req,def=0" json:"IID,omitempty"`
	// * 货物字符串ID
	SID *string `protobuf:"bytes,2,req,def=" json:"SID,omitempty"`
	// * 花费的人民币数量
	RMB *uint32 `protobuf:"varint,3,opt,def=0" json:"RMB,omitempty"`
	// * 增加的RMBPoint
	RMBPoint *uint32 `protobuf:"varint,4,opt,def=0" json:"RMBPoint,omitempty"`
	// * 购买获得的HC
	HC *uint32 `protobuf:"varint,5,opt,def=0" json:"HC,omitempty"`
	// * 额外赠送HC（首次赠送互斥）
	HCGive *uint32 `protobuf:"varint,6,opt,def=0" json:"HCGive,omitempty"`
	// * 额外赠送描述
	CommonDES *string `protobuf:"bytes,7,opt,def=" json:"CommonDES,omitempty"`
	// * 月、年卡持续时间
	CardPeriod *uint32 `protobuf:"varint,8,opt,def=0" json:"CardPeriod,omitempty"`
	// * 月卡描述
	CardDes *string `protobuf:"bytes,9,opt,def=" json:"CardDes,omitempty"`
	// * 首次购买赠送ID
	FirstGiveID *uint32 `protobuf:"varint,10,opt,def=0" json:"FirstGiveID,omitempty"`
	// * 充值项目的图片资源
	Icon             *string `protobuf:"bytes,11,opt,def=" json:"Icon,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PAY) Reset()         { *m = PAY{} }
func (m *PAY) String() string { return proto.CompactTextString(m) }
func (*PAY) ProtoMessage()    {}

const Default_PAY_IID uint32 = 0
const Default_PAY_RMB uint32 = 0
const Default_PAY_RMBPoint uint32 = 0
const Default_PAY_HC uint32 = 0
const Default_PAY_HCGive uint32 = 0
const Default_PAY_CardPeriod uint32 = 0
const Default_PAY_FirstGiveID uint32 = 0

func (m *PAY) GetIID() uint32 {
	if m != nil && m.IID != nil {
		return *m.IID
	}
	return Default_PAY_IID
}

func (m *PAY) GetSID() string {
	if m != nil && m.SID != nil {
		return *m.SID
	}
	return ""
}

func (m *PAY) GetRMB() uint32 {
	if m != nil && m.RMB != nil {
		return *m.RMB
	}
	return Default_PAY_RMB
}

func (m *PAY) GetRMBPoint() uint32 {
	if m != nil && m.RMBPoint != nil {
		return *m.RMBPoint
	}
	return Default_PAY_RMBPoint
}

func (m *PAY) GetHC() uint32 {
	if m != nil && m.HC != nil {
		return *m.HC
	}
	return Default_PAY_HC
}

func (m *PAY) GetHCGive() uint32 {
	if m != nil && m.HCGive != nil {
		return *m.HCGive
	}
	return Default_PAY_HCGive
}

func (m *PAY) GetCommonDES() string {
	if m != nil && m.CommonDES != nil {
		return *m.CommonDES
	}
	return ""
}

func (m *PAY) GetCardPeriod() uint32 {
	if m != nil && m.CardPeriod != nil {
		return *m.CardPeriod
	}
	return Default_PAY_CardPeriod
}

func (m *PAY) GetCardDes() string {
	if m != nil && m.CardDes != nil {
		return *m.CardDes
	}
	return ""
}

func (m *PAY) GetFirstGiveID() uint32 {
	if m != nil && m.FirstGiveID != nil {
		return *m.FirstGiveID
	}
	return Default_PAY_FirstGiveID
}

func (m *PAY) GetIcon() string {
	if m != nil && m.Icon != nil {
		return *m.Icon
	}
	return ""
}

type PAY_ARRAY struct {
	Items            []*PAY `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PAY_ARRAY) Reset()         { *m = PAY_ARRAY{} }
func (m *PAY_ARRAY) String() string { return proto.CompactTextString(m) }
func (*PAY_ARRAY) ProtoMessage()    {}

func (m *PAY_ARRAY) GetItems() []*PAY {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
}
