// Code generated by protoc-gen-go.
// source: ProtobufGen_yybgift.proto
// DO NOT EDIT!

package ProtobufGen

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type YYBGIFT struct {
	// * 礼包ID
	GiftID *uint32 `protobuf:"varint,1,opt,def=0" json:"GiftID,omitempty"`
	// * 礼包类型
	GiftType *uint32 `protobuf:"varint,3,req,def=0" json:"GiftType,omitempty"`
	// * Pkey签名
	Pkey *string `protobuf:"bytes,6,opt,def=" json:"Pkey,omitempty"`
	// * 完成条件数值参数1
	FCValue1         *uint32                  `protobuf:"varint,4,opt,def=0" json:"FCValue1,omitempty"`
	Item_Table       []*YYBGIFT_ItemCondition `protobuf:"bytes,5,rep" json:"Item_Table,omitempty"`
	XXX_unrecognized []byte                   `json:"-"`
}

func (m *YYBGIFT) Reset()         { *m = YYBGIFT{} }
func (m *YYBGIFT) String() string { return proto.CompactTextString(m) }
func (*YYBGIFT) ProtoMessage()    {}

const Default_YYBGIFT_GiftID uint32 = 0
const Default_YYBGIFT_GiftType uint32 = 0
const Default_YYBGIFT_FCValue1 uint32 = 0

func (m *YYBGIFT) GetGiftID() uint32 {
	if m != nil && m.GiftID != nil {
		return *m.GiftID
	}
	return Default_YYBGIFT_GiftID
}

func (m *YYBGIFT) GetGiftType() uint32 {
	if m != nil && m.GiftType != nil {
		return *m.GiftType
	}
	return Default_YYBGIFT_GiftType
}

func (m *YYBGIFT) GetPkey() string {
	if m != nil && m.Pkey != nil {
		return *m.Pkey
	}
	return ""
}

func (m *YYBGIFT) GetFCValue1() uint32 {
	if m != nil && m.FCValue1 != nil {
		return *m.FCValue1
	}
	return Default_YYBGIFT_FCValue1
}

func (m *YYBGIFT) GetItem_Table() []*YYBGIFT_ItemCondition {
	if m != nil {
		return m.Item_Table
	}
	return nil
}

type YYBGIFT_ItemCondition struct {
	// * 奖励物品ID
	ItemID *string `protobuf:"bytes,1,opt,def=" json:"ItemID,omitempty"`
	// * 奖励物品数量
	ItemCount        *uint32 `protobuf:"varint,2,opt,def=0" json:"ItemCount,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *YYBGIFT_ItemCondition) Reset()         { *m = YYBGIFT_ItemCondition{} }
func (m *YYBGIFT_ItemCondition) String() string { return proto.CompactTextString(m) }
func (*YYBGIFT_ItemCondition) ProtoMessage()    {}

const Default_YYBGIFT_ItemCondition_ItemCount uint32 = 0

func (m *YYBGIFT_ItemCondition) GetItemID() string {
	if m != nil && m.ItemID != nil {
		return *m.ItemID
	}
	return ""
}

func (m *YYBGIFT_ItemCondition) GetItemCount() uint32 {
	if m != nil && m.ItemCount != nil {
		return *m.ItemCount
	}
	return Default_YYBGIFT_ItemCondition_ItemCount
}

type YYBGIFT_ARRAY struct {
	Items            []*YYBGIFT `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *YYBGIFT_ARRAY) Reset()         { *m = YYBGIFT_ARRAY{} }
func (m *YYBGIFT_ARRAY) String() string { return proto.CompactTextString(m) }
func (*YYBGIFT_ARRAY) ProtoMessage()    {}

func (m *YYBGIFT_ARRAY) GetItems() []*YYBGIFT {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
}
