[CommonConfig]
runmode = "local"

dynamo_region="cn-north-1"
dynamo_accessKeyID="AKIAPLNPSQYENX3LGB5A"
dynamo_secretAccessKey="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"

httpport = ":8081"

limit_url_regex = ".*" # 这些url做限制（http header和ratelimit）
rate_limit_valid = true                 # 限制访问速度的开关
rate_limit_Average = 10                 # 限速每秒平均数量
rate_limit_Burst = 10                  # 限速每秒最多数量

SentryDSN="https://48a37f2dec3f49c295b71efda5d4b641:7bd6357255584ceea7b187173182e49f@app.getsentry.com/53404"
