[PayConfig]
sdk_http_port=":9080" # 对外公开
dynamo_db_pay_index = "uid-tistatus-index"
SentryDSN="https://be6857e4cfd8492faaecb01944f28e08:0b562b7924074c2181ed45868eaefc47@sentry.io/111080"


[[PayService]]
name="ios"

[PayService.SDK.QUICK]
sdk_url_rel_path="quick/ios/v1/billingcb"
params = ["15088345631881018661579732055577"]

[PayService.Mail.PROD]
db_name="Mail_G201"
dynamo_region="cn-north-1"
db_driver= "DynamoDB"
mongo_url="127.0.0.1"


[PayService.Pay.PROD]
db_name="QuickPay_G201"
dynamo_region="cn-north-1"
db_driver= "DynamoDB"
mongo_url="127.0.0.1"
