[MergeCfg]

etcd_endpoint = ["http://127.0.0.1:2379/"]
# Etcd Root Path 注意以/开头 如 /a4k
etcd_root = "/a4k"
output_path = "."

Gid=0

# 要被merge的两个shard以及DB
ARedis=":6379"
ARedisDB=1
ARedisDBAuth=""
ARedisRank=":6379"
ARedisRankDB=5
ARedisRankDBAuth=""
AShardId=10

BRedis=":6379"
BRedisDB=2
BRedisDBAuth=""
BRedisRank=":6379"
BRedisRankDB=6
BRedisRankDBAuth=""
BShardId=11

# merge后的shard以及DB
ResRedis=":6379"
ResRedisDB=3
ResRedisDBAuth=""
ResRedisRank=":6379"
ResRedisRankDB=7
ResRedisRankDBAuth=""
ResShardId=10 # 此必须是AShardId或BShardId其中之一

DelAccountCorpLvl=30 # 角色多级之下，可能删除， 要求30
DelAccountNotLoginMin=10080 # 角色多少分钟未登录，可能删除，要求7天=10080，方便qa测试是用p.LogoutTime+p.DebugAbsoluteTime