# This part is reloadable!
#graphite_host = "54.223.52.75:2003" #for :2003 tcp of graphite
#graphite_memstats = true
#graphite_gcstats = true
#graphite_flush_interval = 10000000000
#graphite_prefix = "auth"