[PayConfig]
sdk_http_port=":9080" # 对外公开
SentryDSN="https://545171d559674d988b1ae0a426e828e1:0bd84f2f39024ff0afeb8e01784d1339@sentry.io/111078"

[[PayService]]
name="android"

[PayService.SDK.QUICK]
sdk_url_rel_path="quick/android/v1/billingcb"
params = ["36883952788207341780469960584187"]

[PayService.SDK.VIVO]
sdk_url_rel_path="vivo/android/v1/billingcb"
params = ["798fd875853cee449c088c8187984425"]

[PayService.Mail.PROD]
db_name="Mail_G203"
db_driver= "MongoDB"
mongo_url="mongodb://mongouser:eqYofW34E6zH@10.30.4.223:27017/?authSource=admin"

[PayService.Pay.PROD]
db_name="QuickPay_G203"
db_driver= "MongoDB"
mongo_url="mongodb://mongouser:eqYofW34E6zH@10.30.4.18:27017/?authSource=admin"
